name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64

      - name: Build with Maven
        run: mvn -B package -f pom.xml
        
      - name: Set up JFrog CLI and upload to JFrog Artifactory
        run: |
          curl -fL https://getcli.jfrog.io | sh
          ./jfrog rt c rt-server --url="${{ secrets.ARTIFACTORY_URL }}" --apikey="${{ secrets.ARTIFACTORY_API_KEY }}"
          ./jfrog rt u "webapp/target/webapp.war" rt-server:artifactory/libs-snapshot-local/webapp.war
